package GUI.Panels;

/*

COMP 2005 Group Project
A. Ibrahim, H. Dos Prazeres, S. Parson, V. Nagisetty

*/
public class StatisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticsDisplayer
     */
    public StatisticsPanel() {
        initComponents();
    }
    
    public void updatePanel(String s) {
    	jTextPane1.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Statistics"));
        setLayout(new javax.swing.OverlayLayout(this));

        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1);
        jTextPane1.setText("test\n\n\nterasdfsdfsd");
        jTextPane1.setEditable(false);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration                   
}
